# Generated by Django 2.2.1 on 2019-05-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterclone', '0003_twitteruser_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteruser',
            name='following',
            field=models.ManyToManyField(null=True, to='twitterclone.TwitterUser'),
        ),
    ]
