# Generated by Django 2.2.1 on 2019-05-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterclone', '0004_auto_20190517_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteruser',
            name='following',
            field=models.ManyToManyField(blank=True, to='twitterclone.TwitterUser'),
        ),
    ]
